      - name: Run Report Script
        env:
          # Memanggil data dari GitHub Secrets
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          # Tetap biarkan ini jika tidak bersifat rahasia
          TOPIC_ID: '2'
          WEB_URL: 'https://myrepublicsragen.my.id/' 
        run: node .github/scripts/send_report.js
